'use strict';

/**
 * @ngdoc function
 * @name vasaApp.controller:LaporanHarianCtrl
 * @description
 * # LaporanHarianCtrl
 * Controller of the vasaApp
 */
angular.module('vasaApp')
	.controller('LaporanProduksiCtrl',['$scope','$filter','$rootScope','ListCabang','LaporanProduksiList','LoadingScreen',
		function ($scope,$filter,$rootScope,ListCabang,LaporanProduksiList,LoadingScreen) {
		
		$scope.currentCabang = $rootScope.namaCabang;
		$scope.confirm = {};
		$scope.listCabang = [];
		$scope.search = { tglFilter: '' };
		$scope.search.tglFilter = $filter('date')(new Date(), 'MM-yyyy');
		$scope.idCabang = localStorage.getItem('kodeCabang');

		$scope.$watch('isPusat', function() {
			if($scope.isPusat !== null){
				ListCabang.get(function(response){
					$scope.listCabang = response;
				});
			} else {
				$scope.currentCabang ="";
			}
		});

		$scope.currentCabang = $filter('uppercase')($scope.currentCabang);

		$scope.tanggalHariIni = new Date();
		$scope.currentMonth = $filter('uppercase')($filter('date')($scope.tanggalHariIni,'MMMM-yyyy'));
		$scope.items = [];

	$scope.nullChecking = function(data){
		data.forEach(function (element) {
			// element.nama	= (element.nama !== null ?element.nama:'-');
			// element.jumlahArus	= (element.jumlahArus !== null ?element.jumlahArus:'-');
			// element.jumlahGt	= (element.jumlahGt !== null ?element.jumlahGt:'-');
			element.keterangan	= (element.keterangan !== null ?element.keterangan:'-');
			element.tglFilter = $filter('date')(element.tglPermohonan,'MMMM-yyyy');
		});
	};

	$scope.loadData = function() {
		var splitDate = $scope.search.tglFilter.split('-');
		$scope.bulanLaporan = splitDate[0];
		$scope.tahunLaporan = splitDate[1];
		$scope.currentMonth = $filter('uppercase')($filter('date')(new Date($scope.tahunLaporan, $scope.bulanLaporan - 1), 'MMMM-yyyy'));
		LoadingScreen.show();
		LaporanProduksiList.get({
			kodeCabang: $scope.idCabang,
			periode: $scope.bulanLaporan + $scope.tahunLaporan
		},function (response) {
			$scope.items = response;
			$scope.nullChecking($scope.items);
		});	
		LoadingScreen.hide();
	};

		$scope.$watch('search.tglFilter', function (newValue) {
			if (newValue) {
				$scope.loadData();
			}
		});
  
	$scope.generatePdf = function() {

		var namaCabang = $scope.currentCabang;
		var reportDate = $filter('uppercase')($scope.currentMonth);

		var NIPP = localStorage.getItem('NIPP');
		var namaPetugas = localStorage.getItem('nama');
		var tglLaporan = $filter('date')(Date.now(),'dd-MM-yyyy hh:mm:ss');

			var createTabelRow = function(item,no){
				var tabelRow = [
					no.toString(),
					item.kodeCabang,
					item.kodeTerminal,
					item.coaProduksi,
					item.jumlah,
					item.satuanProduksi,
					item.keterangan
				];
				tabelRow.forEach(function(rowItem,index){
					if(rowItem == null) tabelRow[index] = '';
				});
				return tabelRow;
			}

			$scope.bulanLaporan = function(data) {
				return (data.tglFilter === $scope.search.tglFilter);
			};

			var no = 0;
			var laporanProduksi = [];

			laporanProduksi.push([{text: "NO", rowSpan: 2, style:'tableHeader'},
								{text: "KODE CABANG", rowSpan: 2, style:'tableHeader'},
								{text: "KODE TERMINAL", rowSpan: 2, style:'tableHeader'},
								{text: "COA PRODUKSI", rowSpan: 2, style:'tableHeader'},
								{text: "JUMLAH", rowSpan: 2, style:'tableHeader'},
								{text: "SATUAN PRODUKSI", rowSpan: 2, style:'tableHeader'},
			    				{text: "KETERANGAN", rowSpan: 2, style:'tableHeader'}
			    				]);
			laporanProduksi.push(['','','',	'','','','']);

			$scope.items.forEach(function(item,index){
					no++;
					//var tabelRow = createTabelRow(item,no);
					laporanProduksi.push([
						no.toString(),
						item.kodeCabang,
						item.kodeTerminal,
						item.coaProduksi,
						item.jumlah.toString(),
						item.satuanProduksi,
						item.keterangan
					]);
			});

		var pdfContent = {
				pageSize: 'A4',
				pageOrientation: 'portrait',
				pageMargins: [ 40, 60, 40, 60 ],
				style: 'dataTable',
				styles: {
						header: {
							bold: true,
							color: '#000',
							fontSize: 14,
							margin: [0, 0, 0, 8],
							alignment: 'center'
						},
						dataTable: {
							color: '#000',
							fontSize: 10,
							margin: [0, 20, 0, 8],
							alignment: 'center'
						},
						footer: {
							color: '#000',
							alignment: 'justify',
							margin: [20, 20, 20, 10],
							fontSize: 8,
							italics: true
						}
				},
				footer:function(pagenumber, pagecount) {
        		return {
           		text:[
								{ text: 'Generated by ',style:'footer'},
								{ text: namaPetugas,style: 'footer'},
								{ text:' ('+ NIPP +') '+ ' on '+ tglLaporan, style: 'footer'},
								{ text:' from VASA \n', style: 'footer' },
								{ text: pagenumber + ' of ' + pagecount, style: 'footer', alignment:'right', italics:false }
							],margin: [20, 20, 20, 10]
        		};
    		},
				content: [
					{ text: 'LAPORAN PRODUKSI PT PELABUHAN INDONESIA III '+ namaCabang, fontSize: 14, bold: true, alignment:'center',margin: [0, 0, 0, 8] },
					{ text: "BULAN "+ reportDate, fontSize: 14, bold: true, alignment:'center',margin: [0, 0, 0, 8] },
					{
						style: 'dataTable',
						table:{
							headerRows: 2,
							pageBreak: 'before',
							dontBreakRows: true,
							body: laporanProduksi
						// 	[
						// 		[{text: "NO", rowSpan: 2, style:'tableHeader'},
						// 		{text: "KODE CABANG", rowSpan: 2, style:'tableHeader'},
						// 		{text: "KODE TERMINAL", rowSpan: 2, style:'tableHeader'},
						// 		{text: "COA ARUS", rowSpan: 2, style:'tableHeader'},
						// 		{text: "JUMLAH UNIT", rowSpan: 2, style:'tableHeader'},
						// 		{text: "JUMLAH GT", rowSpan: 2, style:'tableHeader'},
			   //  				{text: "KETERANGAN", rowSpan: 2, style:'tableHeader'}
						// 	 ]

						// ].concat(laporanProduksi)

					}
				}
					 ]
		};

	 pdfMake.createPdf(pdfContent).download('Laporan Produksi - ' + namaCabang +' - '+ reportDate +'.pdf');

	};

	$scope.generateExcel = function () {
		var namaCabang = $filter('uppercase')($scope.currentCabang);
		var reportDate = $filter('uppercase')($scope.search.tglFilter);

		var data_type = 'data:application/vnd.ms-excel';
		var table_div = document.getElementById('laporan-produksi');

		var table_html = table_div.outerHTML.replace(/ /g, '%20');
		var a = document.createElement('a');
		a.href = data_type + ', ' + table_html;
		a.download = 'Laporan Produksi - ' + namaCabang + ' - ' + reportDate + '.xls';
		a.click();
	};

}]);
